apiVersion: v1
kind: Pod
metadata:
	name: mssql-pod
	labels:
		app: microservices-seguridad
		type: database
spec:
	containers:
	- name: mssql
	  image: mcr.microsoft.com/mssql/server
	  ports:
		- conatainerPort: 1433
	  env:
	  - name: ACCEPT_EULA
	    value: "Y"
	  - name: SA_PASSWORD
		value: "andres18160"


